name: flutter_video_cast
description: flutter_video_cast let you discover cast devices like Chrome Cast and Apple TV and connect to them.
version: 1.0.4
homepage: https://github.com/PalaTeam/flutter_video_cast

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  stream_transform: ">=1.2.0 <2.0.0"
  flutter_svg: ">=0.0.1 <=0.19.1"
  freezed_annotation: ^0.12.0
  enum_to_string: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # any resolves conflicts automatically
  build_runner: any

  freezed: ^0.12.7
  json_serializable: ^3.5.1
  pedantic: ^1.9.2
  pigeon: ^0.1.19

flutter:
  plugin:
    platforms:
      android:
        package: it.aesys.flutter_video_cast
        pluginClass: FlutterVideoCastPlugin
      ios:
        pluginClass: FlutterVideoCastPlugin

  assets:
    - assets/icons/
